name: Code Style Check

on: push

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install Ruff
      run: pip install ruff
    - name: Lint with Ruff
      run: make ruff

  mypy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      # We need dependencies to properly check all types.
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run MyPy
      run: make mypy

  black:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install Black
      run: pip install black
    - name: Run black
      run: make black
